-- MySQL Script generated by MySQL Workbench
-- Wed Sep 18 14:02:25 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema profil
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema profil
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `profil` DEFAULT CHARACTER SET utf8 ;
USE `profil` ;

-- -----------------------------------------------------
-- Table `profil`.`code_personalite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `profil`.`code_personalite` (
  `idcode_personalite` INT NOT NULL AUTO_INCREMENT,
  `code_personalite` VARCHAR(45) NULL,
  `code_personalite_idcode_personalite` INT NULL,
  PRIMARY KEY (`idcode_personalite`),
  INDEX `fk_code_personalite_code_personalite1_idx` (`code_personalite_idcode_personalite` ASC),
  CONSTRAINT `fk_code_personalite_code_personalite1`
    FOREIGN KEY (`code_personalite_idcode_personalite`)
    REFERENCES `profil`.`code_personalite` (`idcode_personalite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `profil`.`professeur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `profil`.`professeur` (
  `idprofesseur` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  PRIMARY KEY (`idprofesseur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `profil`.`classe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `profil`.`classe` (
  `idclasse` INT NOT NULL AUTO_INCREMENT,
  `nom_classe` VARCHAR(45) NULL,
  `professeur_idprofesseur` INT NULL,
  `total_eleves` INT NULL,
  PRIMARY KEY (`idclasse`, `professeur_idprofesseur`),
  INDEX `fk_classe_professeur1_idx` (`professeur_idprofesseur` ASC),
  CONSTRAINT `fk_classe_professeur1`
    FOREIGN KEY (`professeur_idprofesseur`)
    REFERENCES `profil`.`professeur` (`idprofesseur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `profil`.`etudiant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `profil`.`etudiant` (
  `idetudiant` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `classe_idclasse` INT NULL,
  `code_personalite_idcode_personalite` INT NULL,
  `code_personalite_code_personalite_idcode_personalite` INT NULL,
  `moyenne_back` INT NULL,
  `moyenne_front` INT NULL,
  PRIMARY KEY (`idetudiant`, `classe_idclasse`, `code_personalite_idcode_personalite`, `code_personalite_code_personalite_idcode_personalite`),
  INDEX `fk_etudiant_classe1_idx` (`classe_idclasse` ASC),
  INDEX `fk_etudiant_code_personalite1_idx` (`code_personalite_idcode_personalite` ASC, `code_personalite_code_personalite_idcode_personalite` ASC),
  CONSTRAINT `fk_etudiant_classe1`
    FOREIGN KEY (`classe_idclasse`)
    REFERENCES `profil`.`classe` (`idclasse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_etudiant_code_personalite1`
    FOREIGN KEY (`code_personalite_idcode_personalite`)
    REFERENCES `profil`.`code_personalite` (`idcode_personalite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `profil`.`projet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `profil`.`projet` (
  `idprojet` INT NOT NULL AUTO_INCREMENT,
  `nom_projet` VARCHAR(45) NULL,
  `classe_professeur_idprofesseur` INT NULL,
  `coeff_back` INT NULL,
  `coeff_front` INT NULL,
  `nb_groupes` VARCHAR(45) NULL,
  PRIMARY KEY (`idprojet`, `classe_professeur_idprofesseur`),
  INDEX `fk_projet_classe1_idx` (`classe_professeur_idprofesseur` ASC),
  CONSTRAINT `fk_projet_classe1`
    FOREIGN KEY (`classe_professeur_idprofesseur`)
    REFERENCES `profil`.`classe` (`professeur_idprofesseur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `profil`.`groupes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `profil`.`groupes` (
  `idgroupes` INT NOT NULL AUTO_INCREMENT,
  `projet_idprojet` INT NOT NULL,
  PRIMARY KEY (`idgroupes`, `projet_idprojet`),
  INDEX `fk_groupes_projet1_idx` (`projet_idprojet` ASC),
  CONSTRAINT `fk_groupes_projet1`
    FOREIGN KEY (`projet_idprojet`)
    REFERENCES `profil`.`projet` (`idprojet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `profil`.`technologies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `profil`.`technologies` (
  `idtechnologies` INT NOT NULL AUTO_INCREMENT,
  `nom_technologie` VARCHAR(45) NULL,
  `front_back` TINYINT NULL,
  PRIMARY KEY (`idtechnologies`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `profil`.`technologies_has_projet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `profil`.`technologies_has_projet` (
  `technologies_idtechnologies` INT NOT NULL,
  `projet_idprojet` INT NOT NULL,
  PRIMARY KEY (`technologies_idtechnologies`, `projet_idprojet`),
  INDEX `fk_technologies_has_projet_projet1_idx` (`projet_idprojet` ASC),
  INDEX `fk_technologies_has_projet_technologies1_idx` (`technologies_idtechnologies` ASC),
  CONSTRAINT `fk_technologies_has_projet_technologies1`
    FOREIGN KEY (`technologies_idtechnologies`)
    REFERENCES `profil`.`technologies` (`idtechnologies`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_technologies_has_projet_projet1`
    FOREIGN KEY (`projet_idprojet`)
    REFERENCES `profil`.`projet` (`idprojet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `profil`.`groupes_has_etudiant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `profil`.`groupes_has_etudiant` (
  `groupes_idgroupes` INT NOT NULL,
  `groupes_projet_idprojet` INT NOT NULL,
  `etudiant_idetudiant` INT NOT NULL,
  PRIMARY KEY (`groupes_idgroupes`, `groupes_projet_idprojet`, `etudiant_idetudiant`),
  INDEX `fk_groupes_has_etudiant_etudiant1_idx` (`etudiant_idetudiant` ASC),
  INDEX `fk_groupes_has_etudiant_groupes1_idx` (`groupes_idgroupes` ASC, `groupes_projet_idprojet` ASC),
  CONSTRAINT `fk_groupes_has_etudiant_groupes1`
    FOREIGN KEY (`groupes_idgroupes` , `groupes_projet_idprojet`)
    REFERENCES `profil`.`groupes` (`idgroupes` , `projet_idprojet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_groupes_has_etudiant_etudiant1`
    FOREIGN KEY (`etudiant_idetudiant`)
    REFERENCES `profil`.`etudiant` (`idetudiant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `profil`.`technologies_has_etudiant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `profil`.`technologies_has_etudiant` (
  `technologies_idtechnologies` INT NOT NULL,
  `etudiant_idetudiant` INT NOT NULL,
  `note` INT NULL,
  PRIMARY KEY (`technologies_idtechnologies`, `etudiant_idetudiant`),
  INDEX `fk_technologies_has_etudiant_etudiant1_idx` (`etudiant_idetudiant` ASC),
  INDEX `fk_technologies_has_etudiant_technologies1_idx` (`technologies_idtechnologies` ASC),
  CONSTRAINT `fk_technologies_has_etudiant_technologies1`
    FOREIGN KEY (`technologies_idtechnologies`)
    REFERENCES `profil`.`technologies` (`idtechnologies`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_technologies_has_etudiant_etudiant1`
    FOREIGN KEY (`etudiant_idetudiant`)
    REFERENCES `profil`.`etudiant` (`idetudiant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `profil`.`etudiant_has_projet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `profil`.`etudiant_has_projet` (
  `etudiant_idetudiant` INT NOT NULL,
  `projet_idprojet` INT NOT NULL,
  `note` FLOAT NULL,
  PRIMARY KEY (`etudiant_idetudiant`, `projet_idprojet`),
  INDEX `fk_etudiant_has_projet_projet1_idx` (`projet_idprojet` ASC),
  INDEX `fk_etudiant_has_projet_etudiant1_idx` (`etudiant_idetudiant` ASC),
  CONSTRAINT `fk_etudiant_has_projet_etudiant1`
    FOREIGN KEY (`etudiant_idetudiant`)
    REFERENCES `profil`.`etudiant` (`idetudiant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_etudiant_has_projet_projet1`
    FOREIGN KEY (`projet_idprojet`)
    REFERENCES `profil`.`projet` (`idprojet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
